### ISSUE TITLE
minor: suspicious missing dependency `webbrowser` when using newer versions of Python

### ISSUE THREAD

**Issue by stvnliu** [Ate329/MinecraftBot123#7]
`webbrowser` doesn't appear to exist on PyPI anymore for the newest Python versions. Some alternatives exist including `simple_webbrowser`. Maybe use these instead for future-proofing?

**Comment by Ate329** [comment]
what since when, I didn't know that. I will check that

**Comment by stvnliu** [comment]
It's not urgent. I will make a PR on this as soon as I get a working machine.

**Comment by stvnliu** [comment]
https://pypi.org/project/simple-webbrowser/
Putting a link here to PyPI for future reference

**Comment by Ate329** [comment]
> It's not urgent. I will make a PR on this as soon as I get a working machine.

good good

**Comment by stvnliu** [comment]
Nevermind it turns out `webbrowser` is a built-in Python library lol. Closing.

**Comment by Ate329** [comment]
lollllllll
